### ISSUE TITLE
Where to find code about MULTI-TABLE CardEst(Join)?

### ISSUE THREAD

**Issue by rucjrliu** [wuziniu/FSPN#5]
We are now learning about learned cardinality estimation and FSPN is an excellent model with amazing high performance and innovation, which is without doubt.

Now we have a question about where to find the code about MULTI-TABLE CardEst(Join) in this repository? Look forward to your reply.

**Comment by peipeidawang** [comment]
同蹲

**Comment by wuziniu** [comment]
Sorry about the late reply. The FLAT cardest method, which involves the multi-table estimates is patent by Alibaba. I left the company more than three years ago and when I was there, the open-source of the entire project was not possible because of company policy.

**Comment by peipeidawang** [comment]
Thank you for your email and the information regarding the FLAT cardest method.
I understand that the method involves multi-table estimates and is patented by Alibaba.I was wondering if there might be any possibility to access the code for personal use, in light of any changes in the policy since then.
Thank you again for your time and consideration.



---- Replied Message ----
| From | Ziniu ***@***.***> |
| Date | 12/02/2024 23:09 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [wuziniu/FSPN] Where to find code about MULTI-TABLE CardEst(Join)? (Issue #5) |

Sorry about the late reply. The FLAT cardest method, which involves the multi-table estimates is patent by Alibaba. I left the company more than three years ago and when I was there, the open-source of the entire project was not possible because of company policy.

**Comment by rucjrliu** [comment]
Sorry, I cannot get yet.


---- Replied Message ----
| From | ***@***.***> |
| Date | 12/03/2024 00:05 |
| To | wuziniu/FSPN ***@***.***> |
| Cc | rucjrliu ***@***.***>,
Author ***@***.***> |
| Subject | Re: [wuziniu/FSPN] Where to find code about MULTI-TABLE CardEst(Join)? (Issue #5) |

Thank you for your email and the information regarding the FLAT cardest method.
I understand that the method involves multi-table estimates and is patented by Alibaba.I was wondering if there might be any possibility to access the code for personal use, in light of any changes in the policy since then.
Thank you again for your time and consideration.



---- Replied Message ----
| From | Ziniu ***@***.***> |
| Date | 12/02/2024 23:09 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [wuziniu/FSPN] Where to find code about MULTI-TABLE CardEst(Join)? (Issue #5) |

Sorry about the late reply. The FLAT cardest method, which involves the multi-table estimates is patent by Alibaba. I left the company more than three years ago and when I was there, the open-source of the entire project was not possible because of company policy.

**Comment by wuziniu** [comment]
Thank you for your interest in our work. I have been trying to get my code
ever since I left the company and I still haven't been able to access them
yet. I'll let you know if this situation changes in the future.

Best,
Ziniu

**Comment by rucjrliu** [comment]
Thank you so much :)


---- Replied Message ----
| From | Ziniu ***@***.***> |
| Date | 12/03/2024 00:09 |
| To | wuziniu/FSPN ***@***.***> |
| Cc | rucjrliu ***@***.***>,
Author ***@***.***> |
| Subject | Re: [wuziniu/FSPN] Where to find code about MULTI-TABLE CardEst(Join)? (Issue #5) |

Thank you for your interest in our work. I have been trying to get my code
ever since I left the company and I still haven't been able to access them
yet. I'll let you know if this situation changes in the future.

Best,
Ziniu
